version: "3.8"
services:
  chat-app:
    build:
      context: .
    container_name: chat_app
    depends_on:
      - postgres
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_chat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MINIO_SERVER_ACCESS_KEY=5BXPmkOpjXXxH2PZ
      - MINIO_SERVER_SECRET_KEY=JBoIzp2DyEgaFPhg1nhoWUOdCjG8Rees
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=app_chat
    ports:
      - "5432:5432"
  minio:
      image: 'bitnami/minio:latest'
      ports:
        - '9000:9000'
        - '9001:9001'
      environment:
        - MINIO_ROOT_USER=admin
        - MINIO_ROOT_PASSWORD=root123
